### ISSUE TITLE
Can't get API working

### ISSUE THREAD

**Issue by hlebushekhub** [Royal-lobster/Syncia#78]
I put my API directly into the extension, but something is definitely wrong. Can't tell what's the problem here exactly 

![image](https://github.com/user-attachments/assets/e4959420-7885-482b-a4b7-5f66e5a093a7)

**Comment by Royal-lobster** [comment]
Thats wierd, You copied it from project api key right ? And also it should have all permissions

![CleanShot 2024-09-30 at 09 18 35@2x](https://github.com/user-attachments/assets/af839ba9-9139-4634-b1fe-3cef038557cd)

**Comment by hlebushekhub** [comment]
exactly
![image](https://github.com/user-attachments/assets/784046ab-60fb-4600-9dc4-337021089c83)

**Comment by Royal-lobster** [comment]
Does it work with permissions set to all ?

**Comment by hdnh2006** [comment]
I am also facing similar issues, it looks like the extension is trying to validate the API Key in some way. The endpoint to validate the API should be `/models`

**Comment by Royal-lobster** [comment]
we are validating it by asking the modal to "say ok". and if it throws any error we are considering the api key to be faulty 

https://github.com/Royal-lobster/Syncia/blob/5b91c0cf9afe81a137e38c6091f3535973c8c80a/src/lib/validApiKey.ts#L12

**Comment by Royal-lobster** [comment]
@hlebushekhub @hdnh2006  we pushed a fix relating to this, is it working now ?

**Comment by hdnh2006** [comment]
> @hlebushekhub @hdnh2006 we pushed a fix relating to this, is it working now ?

Thank you, I will try it ASAP and I will provide any feedback.

**Comment by hdnh2006** [comment]
The problem still persists, this is the error I get:
![image](https://github.com/user-attachments/assets/81126af0-c2af-4898-b0c3-eda369a63752)

These are the logs I get from console:
```
TypeError: Cannot read properties of null (reading 'length')
    at new co (getReadableModelName-3cc50390.js:2:7243)
    at jf (getReadableModelName-3cc50390.js:49:762)
    at Lf._generate (getReadableModelName-3cc50390.js:49:11158)
    at async Promise.allSettled (chrome-extension://doeidbfgibihkfbcdlaopieplphgcmmh/src/pages/sidebar/index 0)
    at async Lf._generateUncached (getReadableModelName-3cc50390.js:31:6516)
    at async Lf.invoke (getReadableModelName-3cc50390.js:31:5068)
    at async ag (getReadableModelName-3cc50390.js:49:15341)
    at async onSubmit (sidebar-2dcb0c77.js:1:10994)
ag @ getReadableModelName-3cc50390.js:49
await in ag
onSubmit @ sidebar-2dcb0c77.js:1
ld @ useThemeSync-15ab970a.js:37
id @ useThemeSync-15ab970a.js:37
ud @ useThemeSync-15ab970a.js:37
Yu @ useThemeSync-15ab970a.js:37
Ga @ useThemeSync-15ab970a.js:37
(anonymous) @ useThemeSync-15ab970a.js:37
su @ useThemeSync-15ab970a.js:40
Sa @ useThemeSync-15ab970a.js:37
io @ useThemeSync-15ab970a.js:37
Ai @ useThemeSync-15ab970a.js:37
Cd @ useThemeSync-15ab970a.js:37
```

**Comment by Royal-lobster** [comment]
> However, as I kindly suggested https://github.com/Royal-lobster/Syncia/pull/80#issuecomment-2408901507 and https://github.com/Royal-lobster/Syncia/issues/78#issuecomment-2418908781, the best way to check the API is working is to call the endpoint /models.

This makes sense, it used to be this way, but i believe i changed it to call gpt-3.5 cuz users are missing to give access to all endpoints for the api key. but now we are also supporting custom base urls, perhaps just calling modals is good choice

**Comment by hdnh2006** [comment]
> > However, as I kindly suggested [#80 (comment)](https://github.com/Royal-lobster/Syncia/pull/80#issuecomment-2408901507) and [#78 (comment)](https://github.com/Royal-lobster/Syncia/issues/78#issuecomment-2418908781), the best way to check the API is working is to call the endpoint /models.
> 
> This makes sense, it used to be this way, but i believe i changed it to call gpt-3.5 cuz users are missing to give access to all endpoints for the api key. but now we are also supporting custom base urls, perhaps just calling modals is good choice

Absolutely, the models to be called shouldn't be mocked up in the code but they should be taken directly from the endpoint `models`. For example, for Mistral AI if you run this:
```curl
curl -X GET https://api.mistral.ai/v1/models   -H "Authorization: Bearer sk-mistralAI-token"
```

You get the following json that needs to be parsed:
``` 
{"object":"list","data":[{"id":"ministral-3b-2410","object":"model","created":1729525723,"owned_by":"mistralai","name":"ministral-3b-2410","description":"Official ministral-3b-2410 Mistral AI model","max_context_length":32768,"aliases":["ministral-3b-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"ministral-3b-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"ministral-3b-2410","description":"Official ministral-3b-2410 Mistral AI model","max_context_length":32768,"aliases":["ministral-3b-2410"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"ministral-8b-2410","object":"model","created":1729525723,"owned_by":"mistralai","name":"ministral-8b-2410","description":"Official ministral-8b-2410 Mistral AI model","max_context_length":32768,"aliases":["ministral-8b-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"ministral-8b-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"ministral-8b-2410","description":"Official ministral-8b-2410 Mistral AI model","max_context_length":32768,"aliases":["ministral-8b-2410"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"open-mistral-7b","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-7b","description":"Official open-mistral-7b Mistral AI model","max_context_length":32768,"aliases":["mistral-tiny","mistral-tiny-2312"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-tiny","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-7b","description":"Official open-mistral-7b Mistral AI model","max_context_length":32768,"aliases":["open-mistral-7b","mistral-tiny-2312"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-tiny-2312","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-7b","description":"Official open-mistral-7b Mistral AI model","max_context_length":32768,"aliases":["open-mistral-7b","mistral-tiny"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"open-mistral-nemo","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-nemo","description":"Official open-mistral-nemo Mistral AI model","max_context_length":131072,"aliases":["open-mistral-nemo-2407","mistral-tiny-2407","mistral-tiny-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"open-mistral-nemo-2407","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-nemo","description":"Official open-mistral-nemo Mistral AI model","max_context_length":131072,"aliases":["open-mistral-nemo","mistral-tiny-2407","mistral-tiny-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-tiny-2407","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-nemo","description":"Official open-mistral-nemo Mistral AI model","max_context_length":131072,"aliases":["open-mistral-nemo","open-mistral-nemo-2407","mistral-tiny-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-tiny-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mistral-nemo","description":"Official open-mistral-nemo Mistral AI model","max_context_length":131072,"aliases":["open-mistral-nemo","open-mistral-nemo-2407","mistral-tiny-2407"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"open-mixtral-8x7b","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mixtral-8x7b","description":"Official open-mixtral-8x7b Mistral AI model","max_context_length":32768,"aliases":["mistral-small","mistral-small-2312"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-small","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mixtral-8x7b","description":"Official open-mixtral-8x7b Mistral AI model","max_context_length":32768,"aliases":["open-mixtral-8x7b","mistral-small-2312"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-small-2312","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mixtral-8x7b","description":"Official open-mixtral-8x7b Mistral AI model","max_context_length":32768,"aliases":["open-mixtral-8x7b","mistral-small"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"open-mixtral-8x22b","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mixtral-8x22b","description":"Official open-mixtral-8x22b Mistral AI model","max_context_length":65536,"aliases":["open-mixtral-8x22b-2404"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"open-mixtral-8x22b-2404","object":"model","created":1729525723,"owned_by":"mistralai","name":"open-mixtral-8x22b","description":"Official open-mixtral-8x22b Mistral AI model","max_context_length":65536,"aliases":["open-mixtral-8x22b"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-small-2402","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-small-2402","description":"Official mistral-small-2402 Mistral AI model","max_context_length":32768,"aliases":[],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-small-2409","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-small-2409","description":"Official mistral-small-2409 Mistral AI model","max_context_length":32768,"aliases":["mistral-small-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-small-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-small-2409","description":"Official mistral-small-2409 Mistral AI model","max_context_length":32768,"aliases":["mistral-small-2409"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-medium-2312","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-medium-2312","description":"Official mistral-medium-2312 Mistral AI model","max_context_length":32768,"aliases":["mistral-medium","mistral-medium-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-medium","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-medium-2312","description":"Official mistral-medium-2312 Mistral AI model","max_context_length":32768,"aliases":["mistral-medium-2312","mistral-medium-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-medium-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-medium-2312","description":"Official mistral-medium-2312 Mistral AI model","max_context_length":32768,"aliases":["mistral-medium-2312","mistral-medium"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-large-2402","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-large-2402","description":"Official mistral-large-2402 Mistral AI model","max_context_length":32768,"aliases":[],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"mistral-large-2407","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-large-2407","description":"Official mistral-large-2407 Mistral AI model","max_context_length":131072,"aliases":["mistral-large-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"mistral-large-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-large-2407","description":"Official mistral-large-2407 Mistral AI model","max_context_length":131072,"aliases":["mistral-large-2407"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"codestral-2405","object":"model","created":1729525723,"owned_by":"mistralai","name":"codestral-2405","description":"Official codestral-2405 Mistral AI model","max_context_length":32768,"aliases":["codestral-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":true,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"codestral-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"codestral-2405","description":"Official codestral-2405 Mistral AI model","max_context_length":32768,"aliases":["codestral-2405"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":true,"function_calling":true,"fine_tuning":true,"vision":false},"type":"base"},{"id":"codestral-mamba-2407","object":"model","created":1729525723,"owned_by":"mistralai","name":"codestral-mamba-2407","description":"Official codestral-mamba-2407 Mistral AI model","max_context_length":32768,"aliases":["open-codestral-mamba","codestral-mamba-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"open-codestral-mamba","object":"model","created":1729525723,"owned_by":"mistralai","name":"codestral-mamba-2407","description":"Official codestral-mamba-2407 Mistral AI model","max_context_length":32768,"aliases":["codestral-mamba-2407","codestral-mamba-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"codestral-mamba-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"codestral-mamba-2407","description":"Official codestral-mamba-2407 Mistral AI model","max_context_length":32768,"aliases":["codestral-mamba-2407","open-codestral-mamba"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"},{"id":"pixtral-12b-2409","object":"model","created":1729525723,"owned_by":"mistralai","name":"pixtral-12b-2409","description":"Official pixtral-12b-2409 Mistral AI model","max_context_length":131072,"aliases":["pixtral-12b","pixtral-12b-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":true},"type":"base"},{"id":"pixtral-12b","object":"model","created":1729525723,"owned_by":"mistralai","name":"pixtral-12b-2409","description":"Official pixtral-12b-2409 Mistral AI model","max_context_length":131072,"aliases":["pixtral-12b-2409","pixtral-12b-latest"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":true},"type":"base"},{"id":"pixtral-12b-latest","object":"model","created":1729525723,"owned_by":"mistralai","name":"pixtral-12b-2409","description":"Official pixtral-12b-2409 Mistral AI model","max_context_length":131072,"aliases":["pixtral-12b-2409","pixtral-12b"],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":true},"type":"base"},{"id":"mistral-embed","object":"model","created":1729525723,"owned_by":"mistralai","name":"mistral-embed","description":"Official mistral-embed Mistral AI model","max_context_length":32768,"aliases":[],"deprecation":null,"capabilities":{"completion_chat":true,"completion_fim":false,"function_calling":true,"fine_tuning":false,"vision":false},"type":"base"}]}
```

**Comment by Royal-lobster** [comment]
Nice ! i've merged pr for validating api key from /modals, also for listing available modals to choose from /modals, we can track here: https://github.com/Royal-lobster/Syncia/issues/93

**Comment by hdnh2006** [comment]
> Nice ! i've merged pr for validating api key from /modals, also for listing available modals to choose from /modals, we can track here: #93

Thanks! but the name of the endpoint is not `/modals` but `/models` with "e"

**Comment by hlebushekhub** [comment]
![image](https://github.com/user-attachments/assets/9dddbdc9-123c-46e6-b20b-c696dc7adca5)

Sadly, the problem persists for me

**Comment by Royal-lobster** [comment]
@hlebushekhub I think you are still on a older version
1. Type this in your address bar `chrome:extensions`
2. Check the version number for Syncia it should be 1.5.2

![CleanShot 2024-10-30 at 15 43 16@2x](https://github.com/user-attachments/assets/f316daad-ddf5-4c76-a273-41bfe075cf90)

If its not matching, see if you can remove the extension and install it again from webstore

**Comment by hlebushekhub** [comment]
yeah, you right. after the update it's working properly now!
